// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV27ZAc0B86EiCFR-DN5zc4sUHNvO5xOA',
    appId: '1:576389729643:web:8346b676968e1aa8bb502e',
    messagingSenderId: '576389729643',
    projectId: 'ucpc-a4821',
    authDomain: 'ucpc-a4821.firebaseapp.com',
    storageBucket: 'ucpc-a4821.appspot.com',
    measurementId: 'G-KTXQRSV77J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTcBB3uN9LPcVHGWahX0QhIbTu9FfElDc',
    appId: '1:576389729643:android:ed0599647c5445f0bb502e',
    messagingSenderId: '576389729643',
    projectId: 'ucpc-a4821',
    storageBucket: 'ucpc-a4821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2WhzCjkmgBC2sW6G5HQysTSzuUcYE4E',
    appId: '1:576389729643:ios:12b3d3924a8ad66fbb502e',
    messagingSenderId: '576389729643',
    projectId: 'ucpc-a4821',
    storageBucket: 'ucpc-a4821.appspot.com',
    iosBundleId: 'com.example.ucpcInventoryManagementApp',
  );
}
